/**
 * Health Provider Registry (HPR) Service
 * Implements HPR-FR requirements for provider identity, eligibility, and lifecycle management
 */

import { supabase } from '@/integrations/supabase/client';
import type {
  HealthProvider,
  ProviderLicense,
  ProviderAffiliation,
  ProviderPrivilege,
  ProviderStateTransition,
  EligibilityDecision,
  EligibilityResponse,
  ProviderLifecycleState,
  LicenseStatus,
  ProviderQualification,
} from '@/types/hpr';

export interface CreateProviderInput {
  first_name: string;
  surname: string;
  other_names?: string;
  date_of_birth: string;
  sex: 'male' | 'female' | 'other';
  national_id?: string;
  passport_number?: string;
  email?: string;
  phone?: string;
  nationality?: string;
  cadre: string;
  specialty?: string;
  sub_specialty?: string;
  qualifications?: ProviderQualification[];
  languages?: string[];
}

export interface CreateLicenseInput {
  provider_id: string;
  council_id: string;
  council_name: string;
  registration_number: string;
  license_category: string;
  issue_date: string;
  expiry_date: string;
  source_system?: string;
  source_reference?: string;
}

export interface CreateAffiliationInput {
  provider_id: string;
  facility_id: string;
  facility_name: string;
  employment_type: 'permanent' | 'contract' | 'locum' | 'volunteer' | 'intern' | 'student';
  role: string;
  department?: string;
  position_title?: string;
  privileges: string[];
  start_date: string;
  end_date?: string;
  is_primary?: boolean;
}

export const HPRService = {
  // ==========================================
  // PROVIDER MANAGEMENT
  // ==========================================

  /**
   * Create a new health provider (HPR-FR-001, HPR-FR-002)
   * UPID is auto-generated by database trigger
   */
  async createProvider(input: CreateProviderInput): Promise<HealthProvider> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('health_providers')
      .insert({
        first_name: input.first_name,
        surname: input.surname,
        other_names: input.other_names,
        date_of_birth: input.date_of_birth,
        sex: input.sex,
        national_id: input.national_id,
        passport_number: input.passport_number,
        email: input.email,
        phone: input.phone,
        nationality: input.nationality || 'ZW',
        cadre: input.cadre,
        specialty: input.specialty,
        sub_specialty: input.sub_specialty,
        qualifications: JSON.parse(JSON.stringify(input.qualifications || [])),
        languages: input.languages || ['en'],
        lifecycle_state: 'draft' as const,
        created_by: user?.id,
        upid: '', // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (error) throw error;
    return data as unknown as HealthProvider;
  },

  /**
   * Get a provider by ID
   */
  async getProvider(providerId: string): Promise<HealthProvider | null> {
    const { data, error } = await supabase
      .from('health_providers')
      .select('*')
      .eq('id', providerId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null;
      throw error;
    }
    return data as unknown as HealthProvider;
  },

  /**
   * Get a provider by UPID
   */
  async getProviderByUPID(upid: string): Promise<HealthProvider | null> {
    const { data, error } = await supabase
      .from('health_providers')
      .select('*')
      .eq('upid', upid)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null;
      throw error;
    }
    return data as unknown as HealthProvider;
  },

  /**
   * Get a provider linked to a user account
   */
  async getProviderByUserId(userId: string): Promise<HealthProvider | null> {
    const { data, error } = await supabase
      .from('health_providers')
      .select('*')
      .eq('user_id', userId)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null;
      throw error;
    }
    return data as unknown as HealthProvider;
  },

  /**
   * Search providers
   */
  async searchProviders(query: string, filters?: {
    lifecycle_state?: ProviderLifecycleState;
    cadre?: string;
    limit?: number;
  }): Promise<HealthProvider[]> {
    let queryBuilder = supabase
      .from('health_providers')
      .select('*')
      .eq('is_master_record', true);

    if (query) {
      queryBuilder = queryBuilder.or(
        `first_name.ilike.%${query}%,surname.ilike.%${query}%,upid.ilike.%${query}%,national_id.ilike.%${query}%`
      );
    }

    if (filters?.lifecycle_state) {
      queryBuilder = queryBuilder.eq('lifecycle_state', filters.lifecycle_state);
    }

    if (filters?.cadre) {
      queryBuilder = queryBuilder.eq('cadre', filters.cadre);
    }

    queryBuilder = queryBuilder.limit(filters?.limit || 50);

    const { data, error } = await queryBuilder;
    if (error) throw error;
    return (data || []) as unknown as HealthProvider[];
  },

  /**
   * Update provider details
   */
  async updateProvider(providerId: string, updates: Partial<HealthProvider>): Promise<HealthProvider> {
    const { data: { user } } = await supabase.auth.getUser();
    
    // Convert updates to database-compatible format
    const dbUpdates: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
      updated_by: user?.id,
    };
    
    // Copy allowed fields
    const allowedFields = [
      'first_name', 'surname', 'other_names', 'date_of_birth', 'sex',
      'national_id', 'passport_number', 'photograph_url', 'email', 'phone',
      'nationality', 'cadre', 'specialty', 'sub_specialty', 'languages',
    ];
    
    for (const field of allowedFields) {
      if (field in updates) {
        dbUpdates[field] = updates[field as keyof HealthProvider];
      }
    }
    
    // Handle qualifications specially (convert to JSON)
    if ('qualifications' in updates) {
      dbUpdates.qualifications = JSON.parse(JSON.stringify(updates.qualifications));
    }
    
    const { data, error } = await supabase
      .from('health_providers')
      .update(dbUpdates)
      .eq('id', providerId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as HealthProvider;
  },

  /**
   * Transition provider lifecycle state (HPR-FR-010)
   */
  async transitionState(
    providerId: string,
    newState: ProviderLifecycleState,
    reason?: string,
    councilReference?: string
  ): Promise<HealthProvider> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('health_providers')
      .update({
        lifecycle_state: newState,
        lifecycle_state_reason: reason,
        lifecycle_state_changed_at: new Date().toISOString(),
        lifecycle_state_changed_by: user?.id,
        updated_at: new Date().toISOString(),
        updated_by: user?.id,
      })
      .eq('id', providerId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as HealthProvider;
  },

  /**
   * Link provider to user account (IDP-FR-010)
   */
  async linkToUser(
    providerId: string,
    userId: string,
    verificationMethod: string
  ): Promise<HealthProvider> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('health_providers')
      .update({
        user_id: userId,
        user_linked_at: new Date().toISOString(),
        user_link_verified_by: user?.id,
        user_link_verification_method: verificationMethod,
        updated_at: new Date().toISOString(),
        updated_by: user?.id,
      })
      .eq('id', providerId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as HealthProvider;
  },

  // ==========================================
  // LICENSE MANAGEMENT (HPR-FR-020)
  // ==========================================

  /**
   * Add a license to a provider
   */
  async addLicense(input: CreateLicenseInput): Promise<ProviderLicense> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('provider_licenses')
      .insert({
        ...input,
        status: 'active',
        created_by: user?.id,
      })
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderLicense;
  },

  /**
   * Get all licenses for a provider
   */
  async getProviderLicenses(providerId: string): Promise<ProviderLicense[]> {
    const { data, error } = await supabase
      .from('provider_licenses')
      .select('*')
      .eq('provider_id', providerId)
      .order('expiry_date', { ascending: false });

    if (error) throw error;
    return (data || []) as unknown as ProviderLicense[];
  },

  /**
   * Update license status
   */
  async updateLicenseStatus(
    licenseId: string,
    status: LicenseStatus,
    reason?: string
  ): Promise<ProviderLicense> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('provider_licenses')
      .update({
        status,
        status_reason: reason,
        status_changed_at: new Date().toISOString(),
        status_changed_by: user?.id,
        updated_at: new Date().toISOString(),
      })
      .eq('id', licenseId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderLicense;
  },

  /**
   * Verify a license (mark as verified)
   */
  async verifyLicense(licenseId: string): Promise<ProviderLicense> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('provider_licenses')
      .update({
        last_verified_at: new Date().toISOString(),
        last_verified_by: user?.id,
        updated_at: new Date().toISOString(),
      })
      .eq('id', licenseId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderLicense;
  },

  // ==========================================
  // AFFILIATION MANAGEMENT (HPR-FR-030)
  // ==========================================

  /**
   * Add an affiliation to a provider
   */
  async addAffiliation(input: CreateAffiliationInput): Promise<ProviderAffiliation> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('provider_affiliations')
      .insert({
        ...input,
        is_active: true,
        is_primary: input.is_primary || false,
        created_by: user?.id,
      })
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderAffiliation;
  },

  /**
   * Get all affiliations for a provider
   */
  async getProviderAffiliations(providerId: string): Promise<ProviderAffiliation[]> {
    const { data, error } = await supabase
      .from('provider_affiliations')
      .select('*')
      .eq('provider_id', providerId)
      .order('is_primary', { ascending: false })
      .order('start_date', { ascending: false });

    if (error) throw error;
    return (data || []) as unknown as ProviderAffiliation[];
  },

  /**
   * End an affiliation
   */
  async endAffiliation(
    affiliationId: string,
    reason?: string
  ): Promise<ProviderAffiliation> {
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data, error } = await supabase
      .from('provider_affiliations')
      .update({
        is_active: false,
        end_date: new Date().toISOString().split('T')[0],
        deactivated_at: new Date().toISOString(),
        deactivated_by: user?.id,
        deactivation_reason: reason,
        updated_at: new Date().toISOString(),
      })
      .eq('id', affiliationId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderAffiliation;
  },

  /**
   * Update affiliation privileges
   */
  async updateAffiliationPrivileges(
    affiliationId: string,
    privileges: string[]
  ): Promise<ProviderAffiliation> {
    const { data, error } = await supabase
      .from('provider_affiliations')
      .update({
        privileges,
        updated_at: new Date().toISOString(),
      })
      .eq('id', affiliationId)
      .select()
      .single();

    if (error) throw error;
    return data as unknown as ProviderAffiliation;
  },

  // ==========================================
  // PRIVILEGE TAXONOMY
  // ==========================================

  /**
   * Get all available privileges
   */
  async getPrivileges(): Promise<ProviderPrivilege[]> {
    const { data, error } = await supabase
      .from('provider_privileges_taxonomy')
      .select('*')
      .eq('is_active', true)
      .order('category')
      .order('name');

    if (error) throw error;
    return (data || []) as unknown as ProviderPrivilege[];
  },

  // ==========================================
  // ELIGIBILITY ENGINE (HPR-FR-050)
  // ==========================================

  /**
   * Check provider eligibility using the database function
   */
  async checkEligibility(
    providerId: string,
    requestedRole?: string,
    requestedPrivileges?: string[],
    facilityContext?: string
  ): Promise<EligibilityResponse> {
    const { data, error } = await supabase
      .rpc('check_provider_eligibility', {
        p_provider_id: providerId,
        p_requested_role: requestedRole || null,
        p_requested_privileges: requestedPrivileges || null,
        p_facility_context: facilityContext || null,
      });

    if (error) throw error;
    return data as unknown as EligibilityResponse;
  },

  /**
   * Get eligibility decision history for a provider
   */
  async getEligibilityHistory(providerId: string, limit = 50): Promise<EligibilityDecision[]> {
    const { data, error } = await supabase
      .from('eligibility_decisions')
      .select('*')
      .eq('provider_id', providerId)
      .order('requested_at', { ascending: false })
      .limit(limit);

    if (error) throw error;
    return (data || []) as unknown as EligibilityDecision[];
  },

  // ==========================================
  // STATE TRANSITIONS AUDIT
  // ==========================================

  /**
   * Get state transition history for a provider
   */
  async getStateTransitions(providerId: string): Promise<ProviderStateTransition[]> {
    const { data, error } = await supabase
      .from('provider_state_transitions')
      .select('*')
      .eq('provider_id', providerId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return (data || []) as unknown as ProviderStateTransition[];
  },

  // ==========================================
  // STATISTICS
  // ==========================================

  /**
   * Get provider statistics by lifecycle state
   */
  async getProviderStats(): Promise<Record<ProviderLifecycleState, number>> {
    const { data, error } = await supabase
      .from('health_providers')
      .select('lifecycle_state')
      .eq('is_master_record', true);

    if (error) throw error;

    const stats: Record<string, number> = {
      draft: 0,
      pending_council_verification: 0,
      pending_facility_affiliation: 0,
      active: 0,
      suspended: 0,
      revoked: 0,
      retired: 0,
      deceased: 0,
    };

    (data || []).forEach((p: { lifecycle_state: string }) => {
      if (stats[p.lifecycle_state] !== undefined) {
        stats[p.lifecycle_state]++;
      }
    });

    return stats as Record<ProviderLifecycleState, number>;
  },
};

export default HPRService;
