// Patient Care Tracker Service
// Handles visits, documents, and care state management

import { supabase } from "@/integrations/supabase/client";
import type {
  Visit,
  VisitType,
  VisitStatus,
  VisitOutcome,
  ClinicalDocument,
  ClinicalDocumentType,
  DocumentStatus,
  DocumentReference,
  DischargeSummary,
  TransferSummary,
  PatientCareState,
  CareState,
  FacilityOperationsDashboard,
} from "@/types/patientCareTracker";

// ===========================================
// VISIT MANAGEMENT
// ===========================================

export async function createVisit(data: {
  patientId: string;
  visitType: VisitType;
  facilityId?: string;
  facilityName?: string;
  programmeCode?: string;
  programmeName?: string;
  admissionReason?: string;
  wardId?: string;
  bedId?: string;
}): Promise<Visit | null> {
  try {
    const { data: user } = await supabase.auth.getUser();
    
    const { data: visit, error } = await supabase
      .from('visits')
      .insert([{
        visit_number: '', // Auto-generated by trigger
        patient_id: data.patientId,
        visit_type: data.visitType,
        status: 'active' as const,
        facility_id: data.facilityId,
        facility_name: data.facilityName,
        programme_code: data.programmeCode,
        programme_name: data.programmeName,
        admission_reason: data.admissionReason,
        ward_id: data.wardId,
        bed_id: data.bedId,
        created_by: user?.user?.id,
      }])
      .select()
      .single();

    if (error) throw error;
    return mapToVisit(visit);
  } catch (error) {
    console.error('Error creating visit:', error);
    return null;
  }
}

export async function getPatientVisits(
  patientId: string,
  filters?: {
    status?: VisitStatus[];
    visitType?: VisitType[];
    facilityId?: string;
    dateFrom?: string;
    dateTo?: string;
  }
): Promise<Visit[]> {
  try {
    let query = supabase
      .from('visits')
      .select('*')
      .eq('patient_id', patientId)
      .order('start_date', { ascending: false });

    if (filters?.status?.length) {
      query = query.in('status', filters.status);
    }
    if (filters?.visitType?.length) {
      query = query.in('visit_type', filters.visitType);
    }
    if (filters?.facilityId) {
      query = query.eq('facility_id', filters.facilityId);
    }
    if (filters?.dateFrom) {
      query = query.gte('start_date', filters.dateFrom);
    }
    if (filters?.dateTo) {
      query = query.lte('start_date', filters.dateTo);
    }

    const { data, error } = await query;
    if (error) throw error;
    return (data || []).map(mapToVisit);
  } catch (error) {
    console.error('Error fetching visits:', error);
    return [];
  }
}

export async function getVisitWithEncounters(visitId: string): Promise<Visit | null> {
  try {
    const { data: visit, error: visitError } = await supabase
      .from('visits')
      .select('*')
      .eq('id', visitId)
      .single();

    if (visitError) throw visitError;

    const { data: encounters } = await supabase
      .from('encounters')
      .select('id, encounter_number, encounter_type, status, admission_date, discharge_date, chief_complaint, primary_diagnosis, encounter_sequence')
      .eq('visit_id', visitId)
      .order('encounter_sequence', { ascending: true });

    const mappedVisit = mapToVisit(visit);
    mappedVisit.encounters = (encounters || []).map(e => ({
      id: e.id,
      encounterNumber: e.encounter_number,
      encounterType: e.encounter_type,
      status: e.status,
      admissionDate: e.admission_date,
      dischargeDate: e.discharge_date,
      chiefComplaint: e.chief_complaint,
      primaryDiagnosis: e.primary_diagnosis,
      sequence: e.encounter_sequence || 1,
    }));

    return mappedVisit;
  } catch (error) {
    console.error('Error fetching visit with encounters:', error);
    return null;
  }
}

export async function concludeVisit(
  visitId: string,
  outcome: VisitOutcome,
  outcomeDetails?: string
): Promise<boolean> {
  try {
    const { data: user } = await supabase.auth.getUser();
    
    const { error } = await supabase
      .from('visits')
      .update({
        status: 'completed',
        outcome,
        outcome_details: outcomeDetails,
        outcome_at: new Date().toISOString(),
        outcome_by: user?.user?.id,
        end_date: new Date().toISOString(),
      })
      .eq('id', visitId);

    return !error;
  } catch (error) {
    console.error('Error concluding visit:', error);
    return false;
  }
}

export async function linkEncounterToVisit(
  encounterId: string,
  visitId: string,
  sequence?: number
): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('encounters')
      .update({
        visit_id: visitId,
        encounter_sequence: sequence,
      })
      .eq('id', encounterId);

    return !error;
  } catch (error) {
    console.error('Error linking encounter to visit:', error);
    return false;
  }
}

// ===========================================
// CLINICAL DOCUMENTS
// ===========================================

export async function createClinicalDocument(data: {
  documentType: ClinicalDocumentType;
  patientId: string;
  visitId?: string;
  encounterId?: string;
  title: string;
  contentJson?: Record<string, any>;
  htmlContent?: string;
  patientFriendlyHtml?: string;
  authorId?: string;
  authorName?: string;
  authorRole?: string;
  facilityId?: string;
  facilityName?: string;
}): Promise<ClinicalDocument | null> {
  try {
    const { data: user } = await supabase.auth.getUser();
    
    const { data: doc, error } = await supabase
      .from('clinical_documents')
      .insert([{
        document_number: '', // Auto-generated by trigger
        document_type: data.documentType,
        patient_id: data.patientId,
        visit_id: data.visitId,
        encounter_id: data.encounterId,
        title: data.title,
        status: 'draft' as const,
        version: 1,
        content_json: data.contentJson as any,
        html_content: data.htmlContent,
        patient_friendly_html: data.patientFriendlyHtml,
        author_id: data.authorId || user?.user?.id,
        author_name: data.authorName,
        author_role: data.authorRole,
        authoring_facility_id: data.facilityId,
        authoring_facility_name: data.facilityName,
      }])
      .select()
      .single();

    if (error) throw error;

    // Create document reference for indexing
    await supabase.from('document_references').insert([{
      document_id: doc.id,
      patient_id: data.patientId,
      visit_id: data.visitId,
      encounter_id: data.encounterId,
      document_type: data.documentType,
      document_date: new Date().toISOString(),
      facility_id: data.facilityId,
      facility_name: data.facilityName,
      title: data.title,
      status: 'draft',
      author_name: data.authorName,
    }]);

    return mapToDocument(doc);
  } catch (error) {
    console.error('Error creating clinical document:', error);
    return null;
  }
}

export async function getPatientDocuments(
  patientId: string,
  filters?: {
    documentType?: ClinicalDocumentType[];
    visitId?: string;
    status?: DocumentStatus[];
    dateFrom?: string;
    dateTo?: string;
  }
): Promise<DocumentReference[]> {
  try {
    let query = supabase
      .from('document_references')
      .select('*')
      .eq('patient_id', patientId)
      .order('document_date', { ascending: false });

    if (filters?.documentType?.length) {
      query = query.in('document_type', filters.documentType);
    }
    if (filters?.visitId) {
      query = query.eq('visit_id', filters.visitId);
    }
    if (filters?.status?.length) {
      query = query.in('status', filters.status);
    }
    if (filters?.dateFrom) {
      query = query.gte('document_date', filters.dateFrom);
    }
    if (filters?.dateTo) {
      query = query.lte('document_date', filters.dateTo);
    }

    const { data, error } = await query;
    if (error) throw error;

    return (data || []).map(d => ({
      id: d.id,
      documentId: d.document_id,
      patientId: d.patient_id,
      visitId: d.visit_id,
      encounterId: d.encounter_id,
      documentType: d.document_type,
      documentDate: d.document_date,
      facilityId: d.facility_id,
      facilityName: d.facility_name,
      title: d.title,
      status: d.status,
      authorName: d.author_name,
      tags: d.tags,
    }));
  } catch (error) {
    console.error('Error fetching documents:', error);
    return [];
  }
}

export async function getDocument(documentId: string): Promise<ClinicalDocument | null> {
  try {
    const { data, error } = await supabase
      .from('clinical_documents')
      .select('*')
      .eq('id', documentId)
      .single();

    if (error) throw error;
    return mapToDocument(data);
  } catch (error) {
    console.error('Error fetching document:', error);
    return null;
  }
}

export async function signDocument(documentId: string): Promise<boolean> {
  try {
    const { data: user } = await supabase.auth.getUser();
    const { data: profile } = await supabase
      .from('profiles')
      .select('display_name')
      .eq('user_id', user?.user?.id)
      .single();

    const { error } = await supabase
      .from('clinical_documents')
      .update({
        status: 'final',
        signed_by: user?.user?.id,
        signed_by_name: profile?.display_name,
        signed_at: new Date().toISOString(),
        finalized_at: new Date().toISOString(),
      })
      .eq('id', documentId);

    if (!error) {
      // Update document reference status
      await supabase
        .from('document_references')
        .update({ status: 'final' })
        .eq('document_id', documentId);
    }

    return !error;
  } catch (error) {
    console.error('Error signing document:', error);
    return false;
  }
}

// ===========================================
// PATIENT CARE STATE
// ===========================================

export async function getPatientCareState(patientId: string, visitId?: string): Promise<PatientCareState | null> {
  try {
    let query = supabase
      .from('patient_care_state')
      .select('*')
      .eq('patient_id', patientId);

    if (visitId) {
      query = query.eq('visit_id', visitId);
    }

    const { data, error } = await query.single();
    if (error && error.code !== 'PGRST116') throw error;

    return data ? mapToCareState(data) : null;
  } catch (error) {
    console.error('Error fetching care state:', error);
    return null;
  }
}

export async function updatePatientCareState(
  patientId: string,
  updates: Partial<{
    visitId: string;
    encounterId: string;
    workspaceId: string;
    workspaceName: string;
    servicePoint: string;
    facilityId: string;
    careState: CareState;
    responsibleTeam: string;
    responsibleProviderId: string;
    responsibleProviderName: string;
    nextExpectedAction: string;
    nextActionDueAt: string;
  }>
): Promise<boolean> {
  try {
    const { data: existing } = await supabase
      .from('patient_care_state')
      .select('id')
      .eq('patient_id', patientId)
      .eq('visit_id', updates.visitId || null)
      .single();

    if (existing) {
      const { error } = await supabase
        .from('patient_care_state')
        .update({
          encounter_id: updates.encounterId,
          current_workspace_id: updates.workspaceId,
          current_workspace_name: updates.workspaceName,
          current_service_point: updates.servicePoint,
          facility_id: updates.facilityId,
          care_state: updates.careState,
          responsible_team: updates.responsibleTeam,
          responsible_provider_id: updates.responsibleProviderId,
          responsible_provider_name: updates.responsibleProviderName,
          next_expected_action: updates.nextExpectedAction,
          next_action_due_at: updates.nextActionDueAt,
          last_activity_at: new Date().toISOString(),
        })
        .eq('id', existing.id);

      return !error;
    } else {
      const { error } = await supabase
        .from('patient_care_state')
        .insert([{
          patient_id: patientId,
          visit_id: updates.visitId,
          encounter_id: updates.encounterId,
          current_workspace_id: updates.workspaceId,
          current_workspace_name: updates.workspaceName,
          current_service_point: updates.servicePoint,
          facility_id: updates.facilityId,
          care_state: updates.careState || 'waiting',
          responsible_team: updates.responsibleTeam,
          responsible_provider_id: updates.responsibleProviderId,
          responsible_provider_name: updates.responsibleProviderName,
          next_expected_action: updates.nextExpectedAction,
          next_action_due_at: updates.nextActionDueAt,
        }]);

      return !error;
    }
  } catch (error) {
    console.error('Error updating care state:', error);
    return false;
  }
}

// ===========================================
// FACILITY OPERATIONS
// ===========================================

export async function getFacilityOperationsDashboard(facilityId: string): Promise<FacilityOperationsDashboard | null> {
  try {
    const { data, error } = await supabase
      .from('facility_operations_dashboard')
      .select('*')
      .eq('facility_id', facilityId)
      .single();

    if (error) throw error;

    return {
      facilityId: data.facility_id,
      facilityName: data.facility_name,
      arrivalsToday: data.arrivals_today || 0,
      sortingPending: data.sorting_pending || 0,
      queueBacklog: data.queue_backlog || 0,
      investigationsPending: data.investigations_pending || 0,
      readyForDischarge: data.ready_for_discharge || 0,
      transfersPending: data.transfers_pending || 0,
      stalledFlows: data.stalled_flows || 0,
    };
  } catch (error) {
    console.error('Error fetching operations dashboard:', error);
    return null;
  }
}

export async function getActivePatientsByState(
  facilityId: string,
  careState?: CareState
): Promise<PatientCareState[]> {
  try {
    let query = supabase
      .from('patient_care_state')
      .select('*')
      .eq('facility_id', facilityId)
      .order('state_started_at', { ascending: true });

    if (careState) {
      query = query.eq('care_state', careState);
    }

    const { data, error } = await query;
    if (error) throw error;

    return (data || []).map(mapToCareState);
  } catch (error) {
    console.error('Error fetching active patients:', error);
    return [];
  }
}

// ===========================================
// MAPPERS
// ===========================================

function mapToVisit(data: any): Visit {
  return {
    id: data.id,
    visitNumber: data.visit_number,
    patientId: data.patient_id,
    visitType: data.visit_type,
    status: data.status,
    facilityId: data.facility_id,
    facilityName: data.facility_name,
    programmeCode: data.programme_code,
    programmeName: data.programme_name,
    startDate: data.start_date,
    endDate: data.end_date,
    expectedDischargeDate: data.expected_discharge_date,
    outcome: data.outcome,
    outcomeDetails: data.outcome_details,
    outcomeAt: data.outcome_at,
    outcomeBy: data.outcome_by,
    admissionSource: data.admission_source,
    admissionReason: data.admission_reason,
    wardId: data.ward_id,
    bedId: data.bed_id,
    attendingPhysicianId: data.attending_physician_id,
    transferredFromVisitId: data.transferred_from_visit_id,
    transferredToVisitId: data.transferred_to_visit_id,
    transferReason: data.transfer_reason,
    temporaryIdentityId: data.temporary_identity_id,
    identityReconciledAt: data.identity_reconciled_at,
    summaryGenerated: data.summary_generated || false,
    medsReconciled: data.meds_reconciled || false,
    pendingResultsAssigned: data.pending_results_assigned || false,
    conclusionSignedBy: data.conclusion_signed_by,
    conclusionSignedAt: data.conclusion_signed_at,
    createdAt: data.created_at,
    createdBy: data.created_by,
    updatedAt: data.updated_at,
  };
}

function mapToDocument(data: any): ClinicalDocument {
  return {
    id: data.id,
    documentNumber: data.document_number,
    documentType: data.document_type,
    documentSubtype: data.document_subtype,
    loincCode: data.loinc_code,
    loincDisplay: data.loinc_display,
    patientId: data.patient_id,
    visitId: data.visit_id,
    encounterId: data.encounter_id,
    title: data.title,
    status: data.status,
    version: data.version,
    previousVersionId: data.previous_version_id,
    contentJson: data.content_json,
    contentFhir: data.content_fhir,
    htmlContent: data.html_content,
    patientFriendlyHtml: data.patient_friendly_html,
    pdfPath: data.pdf_path,
    patientFriendlyPdfPath: data.patient_friendly_pdf_path,
    authoringFacilityId: data.authoring_facility_id,
    authoringFacilityName: data.authoring_facility_name,
    authorId: data.author_id,
    authorName: data.author_name,
    authorRole: data.author_role,
    signedBy: data.signed_by,
    signedByName: data.signed_by_name,
    signedAt: data.signed_at,
    signatureHash: data.signature_hash,
    coSigners: data.co_signers,
    amendmentReason: data.amendment_reason,
    amendedSections: data.amended_sections,
    shareToken: data.share_token,
    shareTokenExpiresAt: data.share_token_expires_at,
    createdAt: data.created_at,
    updatedAt: data.updated_at,
    finalizedAt: data.finalized_at,
  };
}

function mapToCareState(data: any): PatientCareState {
  return {
    id: data.id,
    patientId: data.patient_id,
    visitId: data.visit_id,
    encounterId: data.encounter_id,
    currentWorkspaceId: data.current_workspace_id,
    currentWorkspaceName: data.current_workspace_name,
    currentServicePoint: data.current_service_point,
    facilityId: data.facility_id,
    careState: data.care_state,
    stateStartedAt: data.state_started_at,
    responsibleTeam: data.responsible_team,
    responsibleProviderId: data.responsible_provider_id,
    responsibleProviderName: data.responsible_provider_name,
    nextExpectedAction: data.next_expected_action,
    nextActionDueAt: data.next_action_due_at,
    actionOverdue: data.action_overdue || false,
    hasStalledFlow: data.has_stalled_flow || false,
    stallReason: data.stall_reason,
    escalationNeeded: data.escalation_needed || false,
    alerts: data.alerts || [],
    lastActivityAt: data.last_activity_at,
    updatedAt: data.updated_at,
  };
}
