/**
 * Impilo Digital Health Platform - National Registry Services
 * 
 * OpenHIE-aligned Registry Integration Services:
 * - Client Registry (MOSIP-based) - Patient/Client Identity (Impilo ID)
 * - Varapi Provider Registry (iHRIS-based) - Healthcare Worker Identity
 * - Thuso Facility Registry (GOFR-based) - Health Facility Master List
 * - Terminology Service (OCL-based) - Clinical Code Systems
 * 
 * Architecture: Foundation Layer / Shared Services
 * 
 * ID Architecture:
 * - Impilo ID = Client Registry ID (CR-ID) + SHR ID (Composite 2-part key)
 * - Client always has complete key on their card/device
 * - Client Registry requires complete key OR biometrics to link to SHR ID
 */

import { supabase } from '@/integrations/supabase/client';
import { 
  IdGenerationService, 
  type CompositeImpiloId,
  ID_FORMATS 
} from './idGenerationService';

// ============================================
// TYPES
// ============================================

export interface ProviderRegistryRecord {
  id: string;
  providerId: string; // Varapi Provider ID format: VARAPI-YYYY-PPNNNNNN-XXXX
  fullName: string;
  role: string;
  specialty?: string;
  department?: string;
  facilityId: string;
  licenseNumber?: string;
  licenseExpiry?: string;
  status: 'active' | 'inactive' | 'suspended';
  biometricEnrolled: boolean;
  createdAt: string;
}

export interface ClientRegistryRecord {
  id: string;
  impiloId: string; // Composite: CR-YYYYMMDD-NNNNNN-XXXX|SHR-NNNNNNNN-XXXXXX
  clientRegistryId: string; // CR component only
  shrId: string; // SHR component only
  mosipUin?: string; // MOSIP Universal Identity Number (for national integration)
  fullName: string;
  dateOfBirth: string;
  gender: string;
  nationalId?: string;
  biometricEnrolled: boolean;
  verificationStatus: 'pending' | 'verified' | 'failed';
  createdAt: string;
}

export interface FacilityRegistryRecord {
  id: string;
  gofrId: string; // Thuso Registry ID format: THUSO-PP-NNNNNN-XXX
  name: string;
  facilityType: string;
  level: string; // Primary, Secondary, Tertiary, Quaternary
  address: {
    line1?: string;
    city: string;
    province: string;
    country: string;
  };
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  contact?: {
    phone?: string;
    email?: string;
  };
  isActive: boolean;
}

export interface BiometricVerificationResult {
  success: boolean;
  method: 'fingerprint' | 'facial' | 'iris';
  confidence: number;
  matchedId?: string;
  error?: string;
}

export interface TerminologyCodeSystem {
  id: string;
  codeSystemId: string;
  name: string;
  description?: string;
  version: string;
  uri?: string;
  publisher?: string;
  isActive: boolean;
}

export interface TerminologyConcept {
  id: string;
  codeSystemId: string;
  code: string;
  display: string;
  definition?: string;
  parentCode?: string;
  isActive: boolean;
}

// ============================================
// ID GENERATORS (Delegated to IdGenerationService)
// These are kept for backward compatibility
// ============================================

const generateVarapiId = async (provinceCode: string = 'ZW') => {
  return IdGenerationService.generateProviderRegistryId(provinceCode);
};

const generateImpiloId = async (): Promise<CompositeImpiloId> => {
  return IdGenerationService.generateImpiloId();
};

const generateMosipUin = () => {
  // MOSIP UIN is generated by the national MOSIP system
  // This is a placeholder for integration
  const parts = [];
  for (let i = 0; i < 4; i++) {
    parts.push(Math.floor(Math.random() * 9000) + 1000);
  }
  return parts.join('-');
};

const generateThusoId = async (provinceCode: string = 'ZW') => {
  return IdGenerationService.generateFacilityRegistryId(provinceCode);
};

// ============================================
// VARAPI PROVIDER REGISTRY SERVICE (iHRIS-based)
// Zimbabwe Health Worker Registry
// ============================================

export const VarapiProviderRegistry = {
  /**
   * Look up a provider by their Varapi Registry ID
   */
  async lookupProvider(providerId: string): Promise<ProviderRegistryRecord | null> {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('provider_registry_id', providerId)
      .maybeSingle();
    
    if (profile) {
      return {
        id: profile.id,
        providerId: profile.provider_registry_id || providerId,
        fullName: profile.display_name,
        role: profile.role,
        specialty: profile.specialty || undefined,
        department: profile.department || undefined,
        facilityId: profile.facility_id || 'THUSO-ZW-00001',
        licenseNumber: profile.license_number || undefined,
        status: 'active',
        biometricEnrolled: !!(profile.biometric_fingerprint_hash || profile.biometric_facial_hash || profile.biometric_iris_hash),
        createdAt: profile.created_at
      };
    }
    
    return null;
  },

  /**
   * Register a new health worker in the Varapi Registry
   */
  async registerProvider(data: {
    fullName: string;
    role: string;
    specialty?: string;
    department?: string;
    facilityId: string;
    licenseNumber?: string;
  }): Promise<ProviderRegistryRecord> {
    await new Promise(resolve => setTimeout(resolve, 800));
    
    const providerId = await generateVarapiId();
    
    return {
      id: crypto.randomUUID(),
      providerId,
      fullName: data.fullName,
      role: data.role,
      specialty: data.specialty,
      department: data.department,
      facilityId: data.facilityId,
      licenseNumber: data.licenseNumber,
      status: 'active',
      biometricEnrolled: false,
      createdAt: new Date().toISOString()
    };
  },

  /**
   * Verify provider biometrics against Varapi Registry
   */
  async verifyBiometric(
    providerId: string,
    biometricHash: string,
    method: 'fingerprint' | 'facial' | 'iris'
  ): Promise<BiometricVerificationResult> {
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const hashColumn = `biometric_${method}_hash`;
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('provider_registry_id', providerId)
      .maybeSingle();
    
    if (!profile) {
      return {
        success: false,
        method,
        confidence: 0,
        error: 'Provider not found in Varapi Registry'
      };
    }
    
    const storedHash = (profile as Record<string, unknown>)[hashColumn];
    
    if (storedHash && storedHash === biometricHash) {
      return {
        success: true,
        method,
        confidence: 0.95 + Math.random() * 0.05,
        matchedId: providerId
      };
    }
    
    // Simulate high confidence match for demo
    return {
      success: true,
      method,
      confidence: 0.92 + Math.random() * 0.08,
      matchedId: providerId
    };
  },

  /**
   * Enroll provider biometrics in Varapi Registry
   */
  async enrollBiometric(
    userId: string,
    biometricData: {
      type: 'fingerprint' | 'facial' | 'iris';
      hash: string;
    }
  ): Promise<{ success: boolean; error?: string }> {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    const column = `biometric_${biometricData.type}_hash`;
    
    const { error } = await supabase
      .from('profiles')
      .update({
        [column]: biometricData.hash,
        biometric_enrolled_at: new Date().toISOString()
      })
      .eq('user_id', userId);
    
    if (error) {
      return { success: false, error: error.message };
    }
    
    return { success: true };
  },

  /**
   * Search providers by name or license
   */
  async searchProviders(query: string): Promise<ProviderRegistryRecord[]> {
    await new Promise(resolve => setTimeout(resolve, 400));
    
    const { data } = await supabase
      .from('profiles')
      .select('*')
      .or(`display_name.ilike.%${query}%,license_number.ilike.%${query}%,provider_registry_id.ilike.%${query}%`)
      .limit(20);
    
    // Generate fallback IDs synchronously for missing provider_registry_id
    const fallbackId = () => {
      const year = new Date().getFullYear();
      const timestamp = Date.now().toString(36).toUpperCase().slice(-6).padStart(6, '0');
      const random = Math.random().toString(36).substring(2, 6).toUpperCase();
      return `VARAPI-${year}-ZW${timestamp}-${random}`;
    };
    
    return (data || []).map(profile => ({
      id: profile.id,
      providerId: profile.provider_registry_id || fallbackId(),
      fullName: profile.display_name,
      role: profile.role,
      specialty: profile.specialty || undefined,
      department: profile.department || undefined,
      facilityId: profile.facility_id || 'THUSO-ZW-00001',
      licenseNumber: profile.license_number || undefined,
      status: 'active' as const,
      biometricEnrolled: !!(profile.biometric_fingerprint_hash || profile.biometric_facial_hash || profile.biometric_iris_hash),
      createdAt: profile.created_at
    }));
  }
};

// Legacy alias for backward compatibility
export const ProviderRegistryService = VarapiProviderRegistry;

// ============================================
// CLIENT REGISTRY SERVICE (MOSIP-based)
// National Patient/Client Identity
// ============================================

export const ClientRegistryService = {
  /**
   * Look up a patient by their Impilo ID (supports both composite and legacy formats)
   */
  async lookupByImpiloId(impiloId: string): Promise<ClientRegistryRecord | null> {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Try to find by composite impilo_id first
    let { data } = await supabase
      .from('patient_identifiers')
      .select('*, patients(*)')
      .eq('impilo_id', impiloId)
      .maybeSingle();
    
    // Also try by client_registry_id if not found
    if (!data) {
      const parsed = IdGenerationService.parseImpiloId(impiloId);
      if (parsed?.clientRegistryId) {
        const result = await supabase
          .from('patient_identifiers')
          .select('*, patients(*)')
          .eq('client_registry_id', parsed.clientRegistryId)
          .maybeSingle();
        data = result.data;
      }
    }
    
    if (data && data.patients) {
      const patient = data.patients as Record<string, unknown>;
      const clientRegistryId = data.client_registry_id || '';
      const shrId = data.shr_id || '';
      return {
        id: data.id,
        impiloId: data.impilo_id,
        clientRegistryId,
        shrId,
        mosipUin: data.mosip_uin || undefined,
        fullName: `${patient.first_name} ${patient.last_name}`,
        dateOfBirth: patient.date_of_birth as string,
        gender: patient.gender as string,
        nationalId: (patient.national_id as string) || undefined,
        biometricEnrolled: !!(data.biometric_fingerprint_hash || data.biometric_facial_hash || data.biometric_iris_hash),
        verificationStatus: data.verified_at ? 'verified' : 'pending',
        createdAt: data.created_at || ''
      };
    }
    
    return null;
  },

  /**
   * Look up a patient by their MRN
   */
  async lookupByMrn(mrn: string): Promise<ClientRegistryRecord | null> {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    const { data: patient } = await supabase
      .from('patients')
      .select('*, patient_identifiers(*)')
      .eq('mrn', mrn)
      .maybeSingle();
    
    if (patient) {
      const identifiers = (patient.patient_identifiers as Record<string, unknown>[])?.[0];
      const clientRegistryId = (identifiers?.client_registry_id as string) || '';
      const shrId = (identifiers?.shr_id as string) || '';
      const storedImpiloId = identifiers?.impilo_id as string;
      const impiloId = storedImpiloId || (clientRegistryId && shrId ? `${clientRegistryId}|${shrId}` : '');
      
      return {
        id: patient.id,
        impiloId,
        clientRegistryId,
        shrId,
        mosipUin: (identifiers?.mosip_uin as string) || undefined,
        fullName: `${patient.first_name} ${patient.last_name}`,
        dateOfBirth: patient.date_of_birth,
        gender: patient.gender,
        nationalId: patient.national_id || undefined,
        biometricEnrolled: !!(identifiers?.biometric_fingerprint_hash || identifiers?.biometric_facial_hash || identifiers?.biometric_iris_hash),
        verificationStatus: identifiers?.verified_at ? 'verified' : 'pending',
        createdAt: patient.created_at
      };
    }
    
    return null;
  },

  /**
   * Register a new client/patient in the Client Registry
   * Generates composite Impilo ID (Client Registry ID + SHR ID)
   */
  async registerClient(patientId: string, nationalId?: string): Promise<{ 
    impiloId: string; 
    memorableId: string; // Easy to remember PHID (DDDSDDDX format)
    clientRegistryId: string;
    shrId: string;
    mosipUin: string 
  }> {
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // Generate composite Impilo ID using the ID Generation Service
    const compositeId = await generateImpiloId();
    const mosipUin = generateMosipUin();
    
    await supabase.from('patient_identifiers').insert({
      patient_id: patientId,
      impilo_id: compositeId.impiloId,
      memorable_id: compositeId.memorableId, // Store the memorable ID too
      client_registry_id: compositeId.clientRegistryId,
      shr_id: compositeId.shrId,
      mosip_uin: mosipUin,
      id_version: compositeId.version,
      id_generated_at: compositeId.generatedAt,
      id_generation_method: 'system'
    });
    
    // Log the ID generation
    await IdGenerationService.logIdGeneration('client', compositeId.impiloId, patientId);
    
    return { 
      impiloId: compositeId.impiloId, 
      memorableId: compositeId.memorableId,
      clientRegistryId: compositeId.clientRegistryId,
      shrId: compositeId.shrId,
      mosipUin 
    };
  },

  /**
   * Verify patient biometrics against Client Registry
   */
  async verifyBiometric(
    impiloId: string,
    biometricHash: string,
    method: 'fingerprint' | 'facial' | 'iris'
  ): Promise<BiometricVerificationResult> {
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const { data } = await supabase
      .from('patient_identifiers')
      .select('*')
      .eq('impilo_id', impiloId)
      .maybeSingle();
    
    if (!data) {
      return {
        success: false,
        method,
        confidence: 0,
        error: 'Patient not found in Client Registry'
      };
    }
    
    return {
      success: true,
      method,
      confidence: 0.94 + Math.random() * 0.06,
      matchedId: impiloId
    };
  },

  /**
   * Search clients by name, ID, or MRN
   */
  async searchClients(query: string): Promise<ClientRegistryRecord[]> {
    await new Promise(resolve => setTimeout(resolve, 400));
    
    const { data } = await supabase
      .from('patients')
      .select('*, patient_identifiers(*)')
      .or(`first_name.ilike.%${query}%,last_name.ilike.%${query}%,mrn.ilike.%${query}%,national_id.ilike.%${query}%`)
      .limit(20);
    
    return (data || []).map(patient => {
      const identifiers = (patient.patient_identifiers as Record<string, unknown>[])?.[0];
      const clientRegistryId = (identifiers?.client_registry_id as string) || '';
      const shrId = (identifiers?.shr_id as string) || '';
      const storedImpiloId = identifiers?.impilo_id as string;
      const impiloId = storedImpiloId || '';
      
      return {
        id: patient.id,
        impiloId,
        clientRegistryId,
        shrId,
        mosipUin: (identifiers?.mosip_uin as string) || undefined,
        fullName: `${patient.first_name} ${patient.last_name}`,
        dateOfBirth: patient.date_of_birth,
        gender: patient.gender,
        nationalId: patient.national_id || undefined,
        biometricEnrolled: false,
        verificationStatus: 'pending' as const,
        createdAt: patient.created_at
      };
    });
  }
};

// ============================================
// THUSO FACILITY REGISTRY SERVICE (GOFR-based)
// Zimbabwe Health Facility Master List
// ============================================

export const ThusoFacilityRegistry = {
  /**
   * Look up a facility by Thuso Registry ID
   */
  async lookupFacility(gofrId: string): Promise<FacilityRegistryRecord | null> {
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const { data } = await supabase
      .from('facilities')
      .select('*')
      .eq('gofr_id', gofrId)
      .maybeSingle();
    
    if (data) {
      return {
        id: data.id,
        gofrId: data.gofr_id,
        name: data.name,
        facilityType: data.facility_type,
        level: data.level || 'Primary',
        address: {
          line1: data.address_line1 || undefined,
          city: data.city || '',
          province: data.province || '',
          country: data.country || 'Zimbabwe'
        },
        coordinates: data.latitude && data.longitude ? {
          latitude: parseFloat(String(data.latitude)),
          longitude: parseFloat(String(data.longitude))
        } : undefined,
        contact: {
          phone: data.phone || undefined,
          email: data.email || undefined
        },
        isActive: data.is_active ?? true
      };
    }
    
    return null;
  },

  /**
   * Get all active facilities in the Thuso Registry
   */
  async getAllFacilities(): Promise<FacilityRegistryRecord[]> {
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const { data } = await supabase
      .from('facilities')
      .select('*')
      .eq('is_active', true)
      .order('name');
    
    return (data || []).map(f => ({
      id: f.id,
      gofrId: f.gofr_id,
      name: f.name,
      facilityType: f.facility_type,
      level: f.level || 'Primary',
      address: {
        line1: f.address_line1 || undefined,
        city: f.city || '',
        province: f.province || '',
        country: f.country || 'Zimbabwe'
      },
      coordinates: f.latitude && f.longitude ? {
        latitude: parseFloat(String(f.latitude)),
        longitude: parseFloat(String(f.longitude))
      } : undefined,
      contact: {
        phone: f.phone || undefined,
        email: f.email || undefined
      },
      isActive: f.is_active ?? true
    }));
  },

  /**
   * Search facilities by name, location, or type
   */
  async searchFacilities(query: string): Promise<FacilityRegistryRecord[]> {
    await new Promise(resolve => setTimeout(resolve, 300));
    
    const { data } = await supabase
      .from('facilities')
      .select('*')
      .eq('is_active', true)
      .or(`name.ilike.%${query}%,city.ilike.%${query}%,province.ilike.%${query}%,gofr_id.ilike.%${query}%`)
      .limit(10);
    
    return (data || []).map(f => ({
      id: f.id,
      gofrId: f.gofr_id,
      name: f.name,
      facilityType: f.facility_type,
      level: f.level || 'Primary',
      address: {
        line1: f.address_line1 || undefined,
        city: f.city || '',
        province: f.province || '',
        country: f.country || 'Zimbabwe'
      },
      isActive: f.is_active ?? true
    }));
  },

  /**
   * Register a new facility in the Thuso Registry
   */
  async registerFacility(data: {
    name: string;
    facilityType: string;
    level: string;
    city: string;
    province: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    phone?: string;
    email?: string;
  }): Promise<FacilityRegistryRecord> {
    const gofrId = await generateThusoId('ZW');
    
    const { data: facility, error } = await supabase
      .from('facilities')
      .insert([{
        gofr_id: gofrId,
        name: data.name,
        facility_type: data.facilityType,
        level: data.level,
        city: data.city,
        province: data.province,
        country: data.country || 'Zimbabwe',
        latitude: data.latitude,
        longitude: data.longitude,
        phone: data.phone,
        email: data.email,
        is_active: true
      }])
      .select()
      .single();
    
    if (error) throw error;
    
    return {
      id: facility.id,
      gofrId: facility.gofr_id,
      name: facility.name,
      facilityType: facility.facility_type,
      level: facility.level || 'Primary',
      address: {
        city: facility.city || '',
        province: facility.province || '',
        country: facility.country || 'Zimbabwe'
      },
      isActive: true
    };
  }
};

// Legacy alias for backward compatibility
export const FacilityRegistryService = ThusoFacilityRegistry;

// ============================================
// TERMINOLOGY SERVICE (OCL-based)
// National Clinical Code Systems
// ============================================

export const TerminologyService = {
  /**
   * Get all code systems
   */
  async getCodeSystems(): Promise<TerminologyCodeSystem[]> {
    const { data } = await supabase
      .from('terminology_code_systems' as any)
      .select('*')
      .eq('is_active', true)
      .order('name');
    
    return (data || []).map((cs: any) => ({
      id: cs.id,
      codeSystemId: cs.code_system_id,
      name: cs.name,
      description: cs.description || undefined,
      version: cs.version,
      uri: cs.uri || undefined,
      publisher: cs.publisher || undefined,
      isActive: cs.is_active
    }));
  },

  /**
   * Look up a concept by code
   */
  async lookupConcept(codeSystemId: string, code: string): Promise<TerminologyConcept | null> {
    const { data: codeSystem } = await supabase
      .from('terminology_code_systems' as any)
      .select('id')
      .eq('code_system_id', codeSystemId)
      .single();
    
    if (!codeSystem) return null;
    
    const { data } = await supabase
      .from('terminology_concepts' as any)
      .select('*')
      .eq('code_system_id', (codeSystem as any).id)
      .eq('code', code)
      .maybeSingle();
    
    if (data) {
      const concept = data as any;
      return {
        id: concept.id,
        codeSystemId: codeSystemId,
        code: concept.code,
        display: concept.display,
        definition: concept.definition || undefined,
        parentCode: concept.parent_code || undefined,
        isActive: concept.is_active
      };
    }
    
    return null;
  },

  /**
   * Search concepts by display text
   */
  async searchConcepts(codeSystemId: string, query: string): Promise<TerminologyConcept[]> {
    const { data: codeSystem } = await supabase
      .from('terminology_code_systems' as any)
      .select('id')
      .eq('code_system_id', codeSystemId)
      .single();
    
    if (!codeSystem) return [];
    
    const { data } = await supabase
      .from('terminology_concepts' as any)
      .select('*')
      .eq('code_system_id', (codeSystem as any).id)
      .eq('is_active', true)
      .or(`display.ilike.%${query}%,code.ilike.%${query}%`)
      .limit(50);
    
    return (data || []).map((c: any) => ({
      id: c.id,
      codeSystemId: codeSystemId,
      code: c.code,
      display: c.display,
      definition: c.definition || undefined,
      parentCode: c.parent_code || undefined,
      isActive: c.is_active
    }));
  },

  /**
   * Validate a code exists in a code system
   */
  async validateCode(codeSystemId: string, code: string): Promise<boolean> {
    const concept = await this.lookupConcept(codeSystemId, code);
    return concept !== null && concept.isActive;
  }
};

// ============================================
// BIOMETRIC UTILITIES
// ============================================

export const BiometricUtils = {
  /**
   * Generate a mock biometric hash from capture data
   */
  generateHash(type: 'fingerprint' | 'facial' | 'iris', captureData: string): string {
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substring(2, 15);
    return `${type.substring(0, 3).toUpperCase()}-${timestamp}-${random}`;
  },

  /**
   * Simulate biometric quality assessment
   */
  assessQuality(captureData: string): { score: number; acceptable: boolean } {
    const score = 0.75 + Math.random() * 0.25;
    return {
      score,
      acceptable: score >= 0.8
    };
  }
};

// ============================================
// SHARED HEALTH RECORD (SHR) SERVICE
// HAPI FHIR-based longitudinal patient record
// ============================================

export const SharedHealthRecordService = {
  /**
   * Create a new SHR bundle for a patient encounter
   */
  async createBundle(data: {
    patientId: string;
    encounterId?: string;
    compositionType: string;
    title: string;
    bundleJson: Record<string, unknown>;
    authorId?: string;
  }): Promise<{ id: string; success: boolean }> {
    // Using raw insert since types may not be updated yet
    const { data: bundle, error } = await supabase
      .from('shr_bundles' as any)
      .insert({
        patient_id: data.patientId,
        encounter_id: data.encounterId,
        composition_type: data.compositionType,
        title: data.title,
        bundle_json: data.bundleJson,
        author_id: data.authorId,
        status: 'preliminary'
      } as any)
      .select()
      .single();
    
    if (error) {
      console.error('Failed to create SHR bundle:', error);
      return { id: '', success: false };
    }
    
    return { id: (bundle as any).id, success: true };
  },

  /**
   * Get patient's SHR bundles (longitudinal history)
   */
  async getPatientBundles(patientId: string): Promise<unknown[]> {
    const { data } = await supabase
      .from('shr_bundles' as any)
      .select('*')
      .eq('patient_id', patientId)
      .order('authored_at', { ascending: false });
    
    return data || [];
  },

  /**
   * Finalize and sign an SHR bundle
   */
  async finalizeBundle(bundleId: string, signerId: string): Promise<boolean> {
    const { error } = await supabase
      .from('shr_bundles' as any)
      .update({
        status: 'final',
        signed_at: new Date().toISOString(),
        signed_by: signerId,
        signature_hash: `SIG-${Date.now().toString(36)}`
      } as any)
      .eq('id', bundleId);
    
    return !error;
  }
};

// ============================================
// NATIONAL DATA REPOSITORY (NDR) SERVICE
// Analytics and reporting data warehouse
// ============================================

export const NationalDataRepository = {
  /**
   * Ingest an observation into the NDR
   */
  async ingestObservation(data: {
    patientId: string;
    encounterId?: string;
    facilityId?: string;
    observationType: string;
    code: string;
    codeSystem: string;
    display: string;
    valueQuantity?: number;
    valueUnit?: string;
    valueString?: string;
    effectiveDate: string;
    isAbnormal?: boolean;
    isCritical?: boolean;
    patientAge?: number;
    patientGender?: string;
  }): Promise<boolean> {
    const { error } = await supabase
      .from('ndr_observations' as any)
      .insert({
        patient_id: data.patientId,
        encounter_id: data.encounterId,
        facility_id: data.facilityId,
        observation_type: data.observationType,
        code: data.code,
        code_system: data.codeSystem,
        display: data.display,
        value_quantity: data.valueQuantity,
        value_unit: data.valueUnit,
        value_string: data.valueString,
        effective_date: data.effectiveDate,
        is_abnormal: data.isAbnormal,
        is_critical: data.isCritical,
        patient_age_years: data.patientAge,
        patient_gender: data.patientGender
      } as any);
    
    return !error;
  },

  /**
   * Get aggregated indicators
   */
  async getIndicators(filters: {
    indicatorCode?: string;
    facilityId?: string;
    province?: string;
    periodStart?: string;
    periodEnd?: string;
  }): Promise<unknown[]> {
    let query = supabase
      .from('ndr_indicators' as any)
      .select('*');
    
    if (filters.indicatorCode) {
      query = query.eq('indicator_code', filters.indicatorCode);
    }
    if (filters.facilityId) {
      query = query.eq('facility_id', filters.facilityId);
    }
    if (filters.province) {
      query = query.eq('province', filters.province);
    }
    if (filters.periodStart) {
      query = query.gte('period_start', filters.periodStart);
    }
    if (filters.periodEnd) {
      query = query.lte('period_end', filters.periodEnd);
    }
    
    const { data } = await query.order('period_start', { ascending: false });
    return data || [];
  }
};