/**
 * Client Registry Data Hook
 * Provides CRUD operations and queries for the National Client Registry
 */

import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import type { 
  ClientRecord, 
  ClientIdentifier, 
  ClientRelationship,
  ClientDuplicateQueue,
  ClientMergeHistory,
  ClientMatchingRule,
  ClientRegistryCounts,
  ClientLifecycleState 
} from '@/types/clientRegistry';

interface UseClientRegistryOptions {
  status?: ClientLifecycleState | 'all';
  search?: string;
  province?: string;
  limit?: number;
}

export function useClientRegistryData(options: UseClientRegistryOptions = {}) {
  const [clients, setClients] = useState<ClientRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [counts, setCounts] = useState<ClientRegistryCounts>({
    total: 0,
    draft: 0,
    active: 0,
    inactive: 0,
    deceased: 0,
    merged: 0,
    duplicates: 0,
  });
  const { toast } = useToast();

  const fetchClients = useCallback(async () => {
    setLoading(true);
    try {
      let query = supabase
        .from('client_registry')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(options.limit || 100);

      if (options.status && options.status !== 'all') {
        query = query.eq('lifecycle_state', options.status);
      }

      if (options.province) {
        query = query.eq('province', options.province);
      }

      if (options.search) {
        query = query.or(
          `given_names.ilike.%${options.search}%,family_name.ilike.%${options.search}%,health_id.ilike.%${options.search}%,phone_primary.ilike.%${options.search}%`
        );
      }

      const { data, error } = await query;

      if (error) throw error;
      setClients((data as ClientRecord[]) || []);
    } catch (error) {
      console.error('Error fetching clients:', error);
      toast({
        title: 'Error',
        description: 'Failed to fetch client records',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }, [options.status, options.search, options.province, options.limit, toast]);

  const fetchCounts = useCallback(async () => {
    try {
      // Get counts by state
      const { data: stateData } = await supabase
        .from('client_registry')
        .select('lifecycle_state');

      const stateCounts = (stateData || []).reduce((acc, row) => {
        const state = row.lifecycle_state as ClientLifecycleState;
        acc[state] = (acc[state] || 0) + 1;
        return acc;
      }, {} as Record<ClientLifecycleState, number>);

      // Get duplicate count
      const { count: dupCount } = await supabase
        .from('client_duplicate_queue')
        .select('*', { count: 'exact', head: true })
        .eq('status', 'pending');

      setCounts({
        total: stateData?.length || 0,
        draft: stateCounts.draft || 0,
        active: stateCounts.active || 0,
        inactive: stateCounts.inactive || 0,
        deceased: stateCounts.deceased || 0,
        merged: stateCounts.merged || 0,
        duplicates: dupCount || 0,
      });
    } catch (error) {
      console.error('Error fetching counts:', error);
    }
  }, []);

  useEffect(() => {
    fetchClients();
    fetchCounts();
  }, [fetchClients, fetchCounts]);

  const createClient = async (client: {
    given_names: string;
    family_name: string;
    sex: 'male' | 'female' | 'other' | 'unknown';
    date_of_birth?: string;
    [key: string]: unknown;
  }) => {
    try {
      const insertData = {
        given_names: client.given_names,
        family_name: client.family_name,
        sex: client.sex,
        date_of_birth: client.date_of_birth,
        health_id: '', // Will be auto-generated by trigger
        ...client,
      };
      
      const { data, error } = await supabase
        .from('client_registry')
        .insert(insertData)
        .select()
        .single();

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: `Health ID ${data.health_id} issued successfully`,
      });
      
      await fetchClients();
      await fetchCounts();
      return data as ClientRecord;
    } catch (error) {
      console.error('Error creating client:', error);
      toast({
        title: 'Error',
        description: 'Failed to create client record',
        variant: 'destructive',
      });
      throw error;
    }
  };

  const updateClient = async (id: string, updates: Partial<ClientRecord>) => {
    try {
      const { data, error } = await supabase
        .from('client_registry')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Client record updated',
      });
      
      await fetchClients();
      return data as ClientRecord;
    } catch (error) {
      console.error('Error updating client:', error);
      toast({
        title: 'Error',
        description: 'Failed to update client record',
        variant: 'destructive',
      });
      throw error;
    }
  };

  const updateLifecycleState = async (
    id: string, 
    newState: ClientLifecycleState, 
    reason?: string
  ) => {
    try {
      const { error } = await supabase
        .from('client_registry')
        .update({
          lifecycle_state: newState,
          lifecycle_state_reason: reason,
          lifecycle_state_changed_at: new Date().toISOString(),
        })
        .eq('id', id);

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: `Client status changed to ${newState}`,
      });
      
      await fetchClients();
      await fetchCounts();
    } catch (error) {
      console.error('Error updating lifecycle state:', error);
      toast({
        title: 'Error',
        description: 'Failed to update client status',
        variant: 'destructive',
      });
      throw error;
    }
  };

  const markDeceased = async (id: string, deceasedDate: string, source: string) => {
    try {
      const { error } = await supabase
        .from('client_registry')
        .update({
          lifecycle_state: 'deceased',
          deceased_date: deceasedDate,
          deceased_confirmed: true,
          deceased_source: source,
          lifecycle_state_changed_at: new Date().toISOString(),
        })
        .eq('id', id);

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Client marked as deceased',
      });
      
      await fetchClients();
      await fetchCounts();
    } catch (error) {
      console.error('Error marking deceased:', error);
      toast({
        title: 'Error',
        description: 'Failed to mark client as deceased',
        variant: 'destructive',
      });
      throw error;
    }
  };

  return {
    clients,
    loading,
    counts,
    refetch: fetchClients,
    createClient,
    updateClient,
    updateLifecycleState,
    markDeceased,
  };
}

// Hook for client identifiers
export function useClientIdentifiers(clientId?: string) {
  const [identifiers, setIdentifiers] = useState<ClientIdentifier[]>([]);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const fetchIdentifiers = useCallback(async () => {
    if (!clientId) return;
    
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('client_identifiers')
        .select('*')
        .eq('client_id', clientId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setIdentifiers((data as ClientIdentifier[]) || []);
    } catch (error) {
      console.error('Error fetching identifiers:', error);
    } finally {
      setLoading(false);
    }
  }, [clientId]);

  useEffect(() => {
    fetchIdentifiers();
  }, [fetchIdentifiers]);

  const addIdentifier = async (identifier: {
    identifier_type: string;
    identifier_value: string;
    assigning_authority?: string;
    [key: string]: unknown;
  }) => {
    try {
      const insertData = {
        client_id: clientId!,
        identifier_type: identifier.identifier_type,
        identifier_value: identifier.identifier_value,
        assigning_authority: identifier.assigning_authority,
      };
      
      const { data, error } = await supabase
        .from('client_identifiers')
        .insert(insertData)
        .select()
        .single();

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Identifier added',
      });
      
      await fetchIdentifiers();
      return data;
    } catch (error) {
      console.error('Error adding identifier:', error);
      toast({
        title: 'Error',
        description: 'Failed to add identifier',
        variant: 'destructive',
      });
      throw error;
    }
  };

  const verifyIdentifier = async (id: string, method: string) => {
    try {
      const { error } = await supabase
        .from('client_identifiers')
        .update({
          confidence: 'verified',
          verified_at: new Date().toISOString(),
          verification_method: method,
        })
        .eq('id', id);

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Identifier verified',
      });
      
      await fetchIdentifiers();
    } catch (error) {
      console.error('Error verifying identifier:', error);
      toast({
        title: 'Error',
        description: 'Failed to verify identifier',
        variant: 'destructive',
      });
      throw error;
    }
  };

  return {
    identifiers,
    loading,
    refetch: fetchIdentifiers,
    addIdentifier,
    verifyIdentifier,
  };
}

// Hook for client relationships
export function useClientRelationships(clientId?: string) {
  const [relationships, setRelationships] = useState<ClientRelationship[]>([]);
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const fetchRelationships = useCallback(async () => {
    if (!clientId) return;
    
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('client_relationships')
        .select('*')
        .eq('client_id', clientId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setRelationships((data as ClientRelationship[]) || []);
    } catch (error) {
      console.error('Error fetching relationships:', error);
    } finally {
      setLoading(false);
    }
  }, [clientId]);

  useEffect(() => {
    fetchRelationships();
  }, [fetchRelationships]);

  const addRelationship = async (relationship: {
    relationship_type: 'mother' | 'father' | 'guardian' | 'caregiver' | 'spouse' | 'child' | 'sibling' | 'proxy' | 'next_of_kin' | 'emergency_contact';
    related_client_id?: string;
    related_person_name?: string;
    [key: string]: unknown;
  }) => {
    try {
      const insertData = {
        client_id: clientId!,
        relationship_type: relationship.relationship_type,
        related_client_id: relationship.related_client_id,
        related_person_name: relationship.related_person_name,
      };
      
      const { data, error } = await supabase
        .from('client_relationships')
        .insert(insertData)
        .select()
        .single();

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Relationship added',
      });
      
      await fetchRelationships();
      return data;
    } catch (error) {
      console.error('Error adding relationship:', error);
      toast({
        title: 'Error',
        description: 'Failed to add relationship',
        variant: 'destructive',
      });
      throw error;
    }
  };

  return {
    relationships,
    loading,
    refetch: fetchRelationships,
    addRelationship,
  };
}

// Hook for duplicate queue
export function useClientDuplicates() {
  const [duplicates, setDuplicates] = useState<ClientDuplicateQueue[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchDuplicates = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('client_duplicate_queue')
        .select('*')
        .in('status', ['pending', 'reviewing'])
        .order('match_score', { ascending: false });

      if (error) throw error;
      setDuplicates((data as ClientDuplicateQueue[]) || []);
    } catch (error) {
      console.error('Error fetching duplicates:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchDuplicates();
  }, [fetchDuplicates]);

  const resolveAsDuplicate = async (queueId: string, survivingClientId: string) => {
    try {
      const { error } = await supabase
        .from('client_duplicate_queue')
        .update({
          status: 'confirmed_duplicate',
          surviving_client_id: survivingClientId,
          reviewed_at: new Date().toISOString(),
        })
        .eq('id', queueId);

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Marked as duplicate - ready for merge',
      });
      
      await fetchDuplicates();
    } catch (error) {
      console.error('Error resolving duplicate:', error);
      toast({
        title: 'Error',
        description: 'Failed to resolve duplicate',
        variant: 'destructive',
      });
      throw error;
    }
  };

  const resolveAsNotDuplicate = async (queueId: string, notes?: string) => {
    try {
      const { error } = await supabase
        .from('client_duplicate_queue')
        .update({
          status: 'not_duplicate',
          review_notes: notes,
          reviewed_at: new Date().toISOString(),
        })
        .eq('id', queueId);

      if (error) throw error;
      
      toast({
        title: 'Success',
        description: 'Marked as not a duplicate',
      });
      
      await fetchDuplicates();
    } catch (error) {
      console.error('Error resolving:', error);
      toast({
        title: 'Error',
        description: 'Failed to resolve',
        variant: 'destructive',
      });
      throw error;
    }
  };

  return {
    duplicates,
    loading,
    refetch: fetchDuplicates,
    resolveAsDuplicate,
    resolveAsNotDuplicate,
  };
}

// Hook for merge history
export function useClientMergeHistory() {
  const [history, setHistory] = useState<ClientMergeHistory[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchHistory = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('client_merge_history')
        .select('*')
        .order('merged_at', { ascending: false })
        .limit(50);

      if (error) throw error;
      setHistory((data as ClientMergeHistory[]) || []);
    } catch (error) {
      console.error('Error fetching merge history:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchHistory();
  }, [fetchHistory]);

  return {
    history,
    loading,
    refetch: fetchHistory,
  };
}

// Hook for matching rules
export function useClientMatchingRules() {
  const [rules, setRules] = useState<ClientMatchingRule[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchRules = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('client_matching_rules')
        .select('*')
        .order('priority', { ascending: true });

      if (error) throw error;
      setRules((data as ClientMatchingRule[]) || []);
    } catch (error) {
      console.error('Error fetching matching rules:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchRules();
  }, [fetchRules]);

  return {
    rules,
    loading,
    refetch: fetchRules,
  };
}

// Identifier crosswalk search
export async function searchByIdentifier(
  identifierType: string,
  identifierValue: string
): Promise<ClientRecord | null> {
  try {
    const { data: identifier } = await supabase
      .from('client_identifiers')
      .select('client_id')
      .eq('identifier_type', identifierType)
      .eq('identifier_value', identifierValue)
      .eq('status', 'active')
      .single();

    if (!identifier) return null;

    const { data: client } = await supabase
      .from('client_registry')
      .select('*')
      .eq('id', identifier.client_id)
      .single();

    return client as ClientRecord;
  } catch (error) {
    console.error('Error in identifier crosswalk:', error);
    return null;
  }
}

// Health ID verification
export async function verifyHealthId(healthId: string): Promise<{
  valid: boolean;
  client?: ClientRecord;
  status?: string;
}> {
  try {
    const { data, error } = await supabase
      .from('client_registry')
      .select('*')
      .eq('health_id', healthId)
      .single();

    if (error || !data) {
      return { valid: false };
    }

    const client = data as ClientRecord;
    return {
      valid: true,
      client,
      status: client.lifecycle_state,
    };
  } catch (error) {
    return { valid: false };
  }
}
