import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { 
  SortingSession, 
  TemporaryPatientIdentity, 
  PatientSearchResult,
  SortingDeskMetrics,
  ArrivalMode,
  TriageUrgency,
  SortingOutcome,
  IdentityResolutionStatus
} from '@/types/sorting';

interface CreateSessionInput {
  arrival_mode: ArrivalMode;
  facility_id?: string;
  sorting_desk_id?: string;
}

interface TriageInput {
  triage_category: TriageUrgency;
  presenting_complaint: string;
  danger_signs?: string[];
  triage_notes?: string;
}

interface RouteToQueueInput {
  target_queue_id: string;
  priority?: string;
}

interface CreateTempIdentityInput {
  given_name?: string;
  alias?: string;
  sex?: string;
  estimated_age?: number;
  estimated_age_unit?: string;
  reason: string;
}

export function usePatientSorting(facilityId?: string) {
  const [activeSessions, setActiveSessions] = useState<SortingSession[]>([]);
  const [metrics, setMetrics] = useState<SortingDeskMetrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Fetch active sorting sessions
  const fetchActiveSessions = useCallback(async () => {
    try {
      let query = supabase
        .from('sorting_sessions')
        .select(`
          *,
          patient:patients(id, first_name, last_name, mrn, date_of_birth, gender)
        `)
        .eq('status', 'in_progress')
        .order('arrival_time', { ascending: true });

      if (facilityId) {
        query = query.eq('facility_id', facilityId);
      }

      const { data, error: fetchError } = await query;
      if (fetchError) throw fetchError;
      
      setActiveSessions((data || []) as SortingSession[]);
    } catch (err) {
      console.error('Error fetching sorting sessions:', err);
      setError('Failed to fetch active sessions');
    }
  }, [facilityId]);

  // Calculate metrics
  const fetchMetrics = useCallback(async () => {
    try {
      const today = new Date().toISOString().split('T')[0];
      
      let query = supabase
        .from('sorting_sessions')
        .select('*')
        .gte('arrival_time', `${today}T00:00:00`)
        .lte('arrival_time', `${today}T23:59:59`);

      if (facilityId) {
        query = query.eq('facility_id', facilityId);
      }

      const { data, error: fetchError } = await query;
      if (fetchError) throw fetchError;

      const sessions = data || [];
      
      const metrics: SortingDeskMetrics = {
        total_arrivals: sessions.length,
        total_triaged: sessions.filter(s => s.triage_at).length,
        immediate_care_count: sessions.filter(s => s.outcome === 'immediate_care').length,
        queued_count: sessions.filter(s => s.outcome === 'queued').length,
        pending_count: sessions.filter(s => s.status === 'in_progress').length,
        avg_processing_time: null,
        emergency_count: sessions.filter(s => s.triage_category === 'emergency').length,
        very_urgent_count: sessions.filter(s => s.triage_category === 'very_urgent').length,
        urgent_count: sessions.filter(s => s.triage_category === 'urgent').length,
        routine_count: sessions.filter(s => s.triage_category === 'routine').length,
      };

      const completedWithTime = sessions.filter(s => s.processing_time_seconds);
      if (completedWithTime.length > 0) {
        metrics.avg_processing_time = Math.round(
          completedWithTime.reduce((sum, s) => sum + (s.processing_time_seconds || 0), 0) / completedWithTime.length
        );
      }

      setMetrics(metrics);
    } catch (err) {
      console.error('Error fetching metrics:', err);
    }
  }, [facilityId]);

  // Create new sorting session
  const createSession = async (input: CreateSessionInput): Promise<SortingSession | null> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      const { data, error: insertError } = await supabase
        .from('sorting_sessions')
        .insert({
          arrival_mode: input.arrival_mode,
          facility_id: input.facility_id || facilityId,
          sorting_desk_id: input.sorting_desk_id,
          session_number: '', // Auto-generated by trigger
          created_by: user?.id,
        })
        .select()
        .single();

      if (insertError) throw insertError;
      
      await fetchActiveSessions();
      await fetchMetrics();
      
      return data as SortingSession;
    } catch (err) {
      console.error('Error creating session:', err);
      setError('Failed to create sorting session');
      return null;
    }
  };

  // Search patients
  const searchPatients = async (query: string): Promise<PatientSearchResult[]> => {
    if (!query || query.length < 2) return [];

    try {
      const searchTerm = `%${query}%`;
      
      const { data, error: searchError } = await supabase
        .from('patients')
        .select('id, mrn, first_name, last_name, date_of_birth, gender')
        .or(`first_name.ilike.${searchTerm},last_name.ilike.${searchTerm},mrn.ilike.${searchTerm}`)
        .limit(10);

      if (searchError) throw searchError;

      return (data || []).map(p => ({
        id: p.id,
        mrn: p.mrn,
        first_name: p.first_name,
        last_name: p.last_name,
        date_of_birth: p.date_of_birth,
        gender: p.gender,
        ...p,
        matchConfidence: p.mrn.toLowerCase().includes(query.toLowerCase()) ? 'exact' as const : 'probable' as const,
        matchReason: p.mrn.toLowerCase().includes(query.toLowerCase()) ? 'MRN match' : 'Name match',
      }));
    } catch (err) {
      console.error('Error searching patients:', err);
      return [];
    }
  };

  // Confirm patient identity
  const confirmIdentity = async (
    sessionId: string, 
    patientId: string, 
    healthId?: string
  ): Promise<boolean> => {
    try {
      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          patient_id: patientId,
          health_id: healthId,
          identity_status: 'confirmed' as IdentityResolutionStatus,
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;
      
      await fetchActiveSessions();
      return true;
    } catch (err) {
      console.error('Error confirming identity:', err);
      return false;
    }
  };

  // Create temporary identity
  const createTempIdentity = async (
    sessionId: string,
    input: CreateTempIdentityInput
  ): Promise<TemporaryPatientIdentity | null> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();

      const { data, error: insertError } = await supabase
        .from('temporary_patient_identities')
        .insert({
          temp_id: '', // Auto-generated
          given_name: input.given_name,
          alias: input.alias,
          sex: input.sex,
          estimated_age: input.estimated_age,
          estimated_age_unit: input.estimated_age_unit || 'years',
          reason: input.reason,
          sorting_session_id: sessionId,
          facility_id: facilityId,
          created_by: user?.id,
        })
        .select()
        .single();

      if (insertError) throw insertError;

      // Link to session
      await supabase
        .from('sorting_sessions')
        .update({
          temp_identity_id: data.id,
          identity_status: 'temporary' as IdentityResolutionStatus,
        })
        .eq('id', sessionId);

      await fetchActiveSessions();
      return data as TemporaryPatientIdentity;
    } catch (err) {
      console.error('Error creating temp identity:', err);
      return null;
    }
  };

  // Perform triage
  const performTriage = async (
    sessionId: string,
    input: TriageInput
  ): Promise<boolean> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();

      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          triage_category: input.triage_category,
          presenting_complaint: input.presenting_complaint,
          danger_signs: input.danger_signs,
          triage_notes: input.triage_notes,
          triage_by: user?.id,
          triage_at: new Date().toISOString(),
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;
      
      await fetchActiveSessions();
      await fetchMetrics();
      return true;
    } catch (err) {
      console.error('Error performing triage:', err);
      return false;
    }
  };

  // Route to immediate care
  const routeToImmediateCare = async (
    sessionId: string,
    workspaceId?: string
  ): Promise<boolean> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();

      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          outcome: 'immediate_care' as SortingOutcome,
          outcome_at: new Date().toISOString(),
          outcome_by: user?.id,
          immediate_care_workspace_id: workspaceId,
          status: 'completed',
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;
      
      await fetchActiveSessions();
      await fetchMetrics();
      return true;
    } catch (err) {
      console.error('Error routing to immediate care:', err);
      return false;
    }
  };

  // Route to queue
  const routeToQueue = async (
    sessionId: string,
    input: RouteToQueueInput
  ): Promise<string | null> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();

      // Get session details
      const { data: session } = await supabase
        .from('sorting_sessions')
        .select('*, patient:patients(id, first_name, last_name)')
        .eq('id', sessionId)
        .single();

      if (!session) throw new Error('Session not found');

      // Create queue item
      const { data: queueItem, error: queueError } = await supabase
        .from('queue_items')
        .insert({
          queue_id: input.target_queue_id,
          patient_id: session.patient_id,
          temp_identity_id: session.temp_identity_id,
          health_id: session.health_id,
          ticket_number: '', // Auto-generated
          sequence_number: 0, // Auto-generated
          entry_type: session.arrival_mode === 'appointment' ? 'appointment' : 'walk_in',
          arrival_time: session.arrival_time,
          arrival_date: session.arrival_time.split('T')[0],
          reason_for_visit: session.presenting_complaint,
          priority: session.triage_category || 'routine',
          status: 'waiting',
        })
        .select()
        .single();

      if (queueError) throw queueError;

      // Update session
      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          outcome: 'queued' as SortingOutcome,
          outcome_at: new Date().toISOString(),
          outcome_by: user?.id,
          target_queue_id: input.target_queue_id,
          queue_item_id: queueItem.id,
          status: 'completed',
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;

      await fetchActiveSessions();
      await fetchMetrics();
      return queueItem.ticket_number;
    } catch (err) {
      console.error('Error routing to queue:', err);
      return null;
    }
  };

  // Cancel session
  const cancelSession = async (sessionId: string, reason?: string): Promise<boolean> => {
    try {
      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          status: 'cancelled',
          outcome_reason: reason,
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;
      
      await fetchActiveSessions();
      await fetchMetrics();
      return true;
    } catch (err) {
      console.error('Error cancelling session:', err);
      return false;
    }
  };

  // Escalate session
  const escalateSession = async (sessionId: string, reason: string): Promise<boolean> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();

      const { error: updateError } = await supabase
        .from('sorting_sessions')
        .update({
          escalated: true,
          escalated_reason: reason,
          escalated_at: new Date().toISOString(),
          escalated_by: user?.id,
          status: 'escalated',
        })
        .eq('id', sessionId);

      if (updateError) throw updateError;
      
      await fetchActiveSessions();
      return true;
    } catch (err) {
      console.error('Error escalating session:', err);
      return false;
    }
  };

  // Initial fetch and realtime subscription
  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      await Promise.all([fetchActiveSessions(), fetchMetrics()]);
      setLoading(false);
    };

    loadData();

    // Subscribe to realtime updates
    const channel = supabase
      .channel('sorting_sessions_changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'sorting_sessions',
        },
        () => {
          fetchActiveSessions();
          fetchMetrics();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [fetchActiveSessions, fetchMetrics]);

  return {
    activeSessions,
    metrics,
    loading,
    error,
    refetch: fetchActiveSessions,
    createSession,
    searchPatients,
    confirmIdentity,
    createTempIdentity,
    performTriage,
    routeToImmediateCare,
    routeToQueue,
    cancelSession,
    escalateSession,
  };
}
