// IPS (International Patient Summary) Viewer Component
import { useState, useEffect } from "react";
import { format } from "date-fns";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  FileText,
  Download,
  Share2,
  RefreshCw,
  QrCode,
  Clock,
  AlertTriangle,
  Pill,
  Heart,
  Syringe,
  Activity,
  FileImage,
  Stethoscope,
  Shield,
  Copy,
  Check,
  Loader2,
} from "lucide-react";
import { usePatientSummary } from "@/hooks/useSummaries";
import type { ShareOptions, RecipientType, AccessLevel } from "@/types/summary";
import { toast } from "sonner";

interface PatientSummaryViewerProps {
  patientId: string;
  patientName?: string;
  healthId?: string;
  onClose?: () => void;
}

export function PatientSummaryViewer({
  patientId,
  patientName,
  healthId,
  onClose,
}: PatientSummaryViewerProps) {
  const { ips, loading, generating, fetchIPS, generateNewIPS, shareIPS } = usePatientSummary(patientId);
  const [showShareDialog, setShowShareDialog] = useState(false);
  const [shareOptions, setShareOptions] = useState<ShareOptions>({
    recipientType: 'provider',
    accessLevel: 'full',
    expiresInHours: 24,
    generateQR: true,
  });
  const [shareToken, setShareToken] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showQR, setShowQR] = useState(false);

  useEffect(() => {
    fetchIPS();
  }, [fetchIPS]);

  const handleGenerate = async (trigger: 'on_demand' | 'emergency' = 'on_demand') => {
    await generateNewIPS({
      trigger,
      accessLevel: 'full',
      purpose: trigger === 'emergency' ? 'Emergency access' : 'Requested by provider',
    });
  };

  const handleShare = async () => {
    const token = await shareIPS(shareOptions);
    if (token) {
      setShareToken(token.token);
      setShareUrl(token.qrCodeUrl || `${window.location.origin}/shared/ips/${token.token}`);
    }
  };

  const handleCopyLink = () => {
    if (shareUrl) {
      navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      toast.success('Link copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!ips) return;
    
    // Create a simple PDF-like download (in production, use proper PDF generation)
    const content = `
INTERNATIONAL PATIENT SUMMARY (IPS)
=====================================

Patient: ${patientName || 'Unknown'}
Health ID: ${healthId || ips.healthId || 'N/A'}
Generated: ${format(new Date(ips.generatedAt), 'PPpp')}

ALLERGIES
---------
${ips.allergies.map(a => `• ${a.substance}${a.reaction ? ` - ${a.reaction}` : ''}`).join('\n')}

MEDICATIONS
-----------
${ips.medications.map(m => `• ${m.name} ${m.dose || ''} ${m.frequency || ''}`).join('\n')}

CONDITIONS
----------
${ips.conditions.map(c => `• ${c.name} (${c.status})`).join('\n')}

RECENT VITAL SIGNS
------------------
${ips.vitalSigns.map(v => `• ${v.type}: ${v.value} ${v.unit}`).join('\n')}

---
Generated by Impilo EHR
Document ID: ${ips.id}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `IPS_${healthId || patientId}_${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Patient Summary downloaded');
  };

  if (loading) {
    return (
      <Card className="w-full">
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="w-full">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-primary" />
              International Patient Summary (IPS)
            </CardTitle>
            <CardDescription>
              {patientName && <span className="font-medium">{patientName}</span>}
              {healthId && <span className="ml-2 text-xs">• {healthId}</span>}
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            {ips ? (
              <>
                <Badge variant="outline" className="text-xs">
                  <Clock className="h-3 w-3 mr-1" />
                  {format(new Date(ips.generatedAt), 'PP')}
                </Badge>
                <Button size="sm" variant="outline" onClick={() => handleGenerate('on_demand')} disabled={generating}>
                  {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                </Button>
              </>
            ) : (
              <Button onClick={() => handleGenerate('on_demand')} disabled={generating}>
                {generating ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4 mr-2" />
                    Generate IPS
                  </>
                )}
              </Button>
            )}
          </div>
        </div>
      </CardHeader>

      {ips ? (
        <>
          <div className="px-6 pb-3 flex gap-2">
            <Button size="sm" variant="outline" onClick={handleDownload}>
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
            <Button size="sm" variant="outline" onClick={() => setShowShareDialog(true)}>
              <Share2 className="h-4 w-4 mr-2" />
              Share
            </Button>
            <Button size="sm" variant="outline" onClick={() => setShowQR(true)}>
              <QrCode className="h-4 w-4 mr-2" />
              QR Code
            </Button>
          </div>

          <CardContent>
            <Tabs defaultValue="allergies" className="w-full">
              <TabsList className="grid w-full grid-cols-6">
                <TabsTrigger value="allergies" className="text-xs">
                  <AlertTriangle className="h-3 w-3 mr-1" />
                  Allergies
                </TabsTrigger>
                <TabsTrigger value="medications" className="text-xs">
                  <Pill className="h-3 w-3 mr-1" />
                  Meds
                </TabsTrigger>
                <TabsTrigger value="conditions" className="text-xs">
                  <Heart className="h-3 w-3 mr-1" />
                  Conditions
                </TabsTrigger>
                <TabsTrigger value="vitals" className="text-xs">
                  <Activity className="h-3 w-3 mr-1" />
                  Vitals
                </TabsTrigger>
                <TabsTrigger value="labs" className="text-xs">
                  <Stethoscope className="h-3 w-3 mr-1" />
                  Labs
                </TabsTrigger>
                <TabsTrigger value="imaging" className="text-xs">
                  <FileImage className="h-3 w-3 mr-1" />
                  Imaging
                </TabsTrigger>
              </TabsList>

              <ScrollArea className="h-[300px] mt-4">
                <TabsContent value="allergies" className="space-y-3">
                  {ips.allergies.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No allergies recorded</p>
                  ) : (
                    ips.allergies.map((allergy, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                        <div>
                          <p className="font-medium">{allergy.substance}</p>
                          {allergy.reaction && (
                            <p className="text-sm text-muted-foreground">{allergy.reaction}</p>
                          )}
                        </div>
                        {allergy.severity && (
                          <Badge variant={allergy.severity === 'severe' ? 'destructive' : 'secondary'}>
                            {allergy.severity}
                          </Badge>
                        )}
                      </div>
                    ))
                  )}
                </TabsContent>

                <TabsContent value="medications" className="space-y-3">
                  {ips.medications.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No active medications</p>
                  ) : (
                    ips.medications.map((med, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                        <div>
                          <p className="font-medium">{med.name}</p>
                          <p className="text-sm text-muted-foreground">
                            {[med.dose, med.route, med.frequency].filter(Boolean).join(' • ')}
                          </p>
                        </div>
                        <Badge variant={med.status === 'active' ? 'default' : 'secondary'}>
                          {med.status}
                        </Badge>
                      </div>
                    ))
                  )}
                </TabsContent>

                <TabsContent value="conditions" className="space-y-3">
                  {ips.conditions.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No conditions recorded</p>
                  ) : (
                    ips.conditions.map((condition, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                        <div>
                          <p className="font-medium">{condition.name}</p>
                          {condition.onsetDate && (
                            <p className="text-sm text-muted-foreground">
                              Since {format(new Date(condition.onsetDate), 'PP')}
                            </p>
                          )}
                        </div>
                        <Badge variant={condition.status === 'active' ? 'default' : 'secondary'}>
                          {condition.status}
                        </Badge>
                      </div>
                    ))
                  )}
                </TabsContent>

                <TabsContent value="vitals" className="space-y-3">
                  {ips.vitalSigns.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No recent vital signs</p>
                  ) : (
                    <div className="grid grid-cols-2 gap-3">
                      {ips.vitalSigns.map((vital, i) => (
                        <div key={i} className="p-3 bg-muted/50 rounded-lg">
                          <p className="text-sm text-muted-foreground">{vital.type}</p>
                          <p className="text-lg font-semibold">
                            {vital.value} <span className="text-sm font-normal">{vital.unit}</span>
                          </p>
                        </div>
                      ))}
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="labs" className="space-y-3">
                  {ips.diagnosticResults.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No recent lab results</p>
                  ) : (
                    ips.diagnosticResults.map((result, i) => (
                      <div key={i} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                        <div>
                          <p className="font-medium">{result.testName}</p>
                          <p className="text-sm text-muted-foreground">
                            {format(new Date(result.date), 'PP')}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="font-medium">{result.value} {result.unit}</p>
                          {result.interpretation && (
                            <Badge variant={result.interpretation === 'critical' ? 'destructive' : 'secondary'}>
                              {result.interpretation}
                            </Badge>
                          )}
                        </div>
                      </div>
                    ))
                  )}
                </TabsContent>

                <TabsContent value="imaging" className="space-y-3">
                  {ips.imagingSummary.length === 0 ? (
                    <p className="text-muted-foreground text-sm">No recent imaging studies</p>
                  ) : (
                    ips.imagingSummary.map((study, i) => (
                      <div key={i} className="p-3 bg-muted/50 rounded-lg">
                        <div className="flex items-center justify-between">
                          <p className="font-medium">{study.studyType}</p>
                          <Badge variant="outline">{study.modality}</Badge>
                        </div>
                        <p className="text-sm text-muted-foreground mt-1">
                          {format(new Date(study.date), 'PP')}
                        </p>
                        {study.findings && (
                          <p className="text-sm mt-2">{study.findings}</p>
                        )}
                      </div>
                    ))
                  )}
                </TabsContent>
              </ScrollArea>
            </Tabs>

            <Separator className="my-4" />

            <div className="flex items-center justify-between text-xs text-muted-foreground">
              <span>Source: {ips.sourceSystems.join(', ')}</span>
              <span>{ips.authoringOrganization}</span>
            </div>
          </CardContent>
        </>
      ) : (
        <CardContent>
          <div className="text-center py-8">
            <Shield className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="font-medium mb-2">No Patient Summary Available</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Generate an International Patient Summary to view essential health information.
            </p>
            <Button onClick={() => handleGenerate('on_demand')} disabled={generating}>
              {generating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <FileText className="h-4 w-4 mr-2" />
                  Generate IPS
                </>
              )}
            </Button>
          </div>
        </CardContent>
      )}

      {/* Share Dialog */}
      <Dialog open={showShareDialog} onOpenChange={setShowShareDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Share Patient Summary</DialogTitle>
            <DialogDescription>
              Create a secure, time-limited share link for this patient summary.
            </DialogDescription>
          </DialogHeader>

          {shareUrl ? (
            <div className="space-y-4">
              <div className="p-4 bg-muted rounded-lg">
                <Label className="text-xs text-muted-foreground">Share Link</Label>
                <div className="flex items-center gap-2 mt-1">
                  <Input value={shareUrl} readOnly className="text-sm" />
                  <Button size="sm" variant="outline" onClick={handleCopyLink}>
                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  </Button>
                </div>
              </div>
              <Button className="w-full" onClick={() => { setShareUrl(null); setShowShareDialog(false); }}>
                Done
              </Button>
            </div>
          ) : (
            <>
              <div className="space-y-4">
                <div>
                  <Label>Recipient Type</Label>
                  <Select
                    value={shareOptions.recipientType}
                    onValueChange={(v) => setShareOptions(prev => ({ ...prev, recipientType: v as RecipientType }))}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="provider">Healthcare Provider</SelectItem>
                      <SelectItem value="facility">Healthcare Facility</SelectItem>
                      <SelectItem value="patient">Patient</SelectItem>
                      <SelectItem value="caregiver">Caregiver</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Access Level</Label>
                  <Select
                    value={shareOptions.accessLevel}
                    onValueChange={(v) => setShareOptions(prev => ({ ...prev, accessLevel: v as AccessLevel }))}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="full">Full Access</SelectItem>
                      <SelectItem value="redacted">Redacted (Sensitive info hidden)</SelectItem>
                      <SelectItem value="patient_friendly">Patient-Friendly View</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Expires In</Label>
                  <Select
                    value={shareOptions.expiresInHours.toString()}
                    onValueChange={(v) => setShareOptions(prev => ({ ...prev, expiresInHours: parseInt(v) }))}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="1">1 hour</SelectItem>
                      <SelectItem value="24">24 hours</SelectItem>
                      <SelectItem value="72">3 days</SelectItem>
                      <SelectItem value="168">7 days</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <DialogFooter>
                <Button variant="outline" onClick={() => setShowShareDialog(false)}>
                  Cancel
                </Button>
                <Button onClick={handleShare}>
                  <Share2 className="h-4 w-4 mr-2" />
                  Create Share Link
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* QR Code Dialog */}
      <Dialog open={showQR} onOpenChange={setShowQR}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Quick Share QR Code</DialogTitle>
            <DialogDescription>
              Scan this QR code to access the patient summary
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col items-center py-6">
            <div className="w-48 h-48 bg-muted rounded-lg flex items-center justify-center mb-4">
              <QrCode className="h-32 w-32 text-muted-foreground" />
            </div>
            <p className="text-sm text-muted-foreground text-center">
              QR code contains a secure, time-limited access link
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowQR(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
